export const BANK_DATA = [
  {
    label: '은행',
    options: [
      { label: '국민은행', value: '0004' },
      { label: '농협은행', value: '0011' },
      { label: '신한은행', value: '0088' },
      { label: '우리은행', value: '0020' },
      { label: '하나은행', value: '0081' },
      { label: '토스뱅크', value: '0092' },
      { label: '카카오뱅크', value: '0090' },
      { label: '케이뱅크', value: '0089' },
      { label: '기업은행', value: '0003' },
      { label: 'SC제일은행', value: '0023' },
      { label: '한국씨티은행', value: '0027' },
      { label: '아이엠뱅크', value: '0031' },
      { label: '수협은행', value: '0007' },
      { label: '신협중앙회', value: '0048' },
      { label: '새마을금고', value: '0045' },
      { label: '우체국', value: '0071' },
      { label: '부산은행', value: '0032' },
      { label: '경남은행', value: '0039' },
      { label: '광주은행', value: '0034' },
      { label: '전북은행', value: '0037' },
      { label: '제주은행', value: '0035' },
      { label: '산업은행', value: '0002' },
      { label: '산림조합중앙회', value: '0064' },
      { label: '농축협', value: '0012' },
    ],
  },
  {
    label: '증권사',
    options: [
      { label: '미래에셋증권', value: '0238' },
      { label: '삼성증권', value: '0240' },
      { label: 'NH투자증권', value: '0247' },
      { label: '한국투자증권', value: '0243' },
      { label: 'KB증권', value: '0218' },
      { label: '키움증권', value: '0264' },
      { label: '메리츠증권', value: '0287' },
      { label: '하나증권', value: '0270' },
      { label: '신한투자증권', value: '0278' },
      { label: '토스증권', value: '0271' },
      { label: '카카오페이증권', value: '0288' },
      { label: '우리투자증권', value: '0294' },
      { label: '유안타증권', value: '0209' },
      { label: '다올투자증권', value: '0227' },
      { label: '교보증권', value: '0261' },
      { label: '아이엠증권', value: '0262' },
      { label: '현대차증권', value: '0263' },
      { label: 'LS증권', value: '0265' },
      { label: 'SK증권', value: '0266' },
      { label: '대신증권', value: '0267' },
      { label: '한화투자증권', value: '0269' },
      { label: 'DB금융투자', value: '0279' },
      { label: '유진투자증권', value: '0280' },
      { label: '부국증권', value: '0290' },
      { label: '신영증권', value: '0291' },
      { label: '케이프증권', value: '0292' },
    ],
  },
]

export const DATE_OF_PAYMENT_DATA = [
  { label: '매월 1일', value: 1 },
  { label: '매월 5일', value: 5 },
  { label: '매월 10일', value: 10 },
  { label: '매월 15일', value: 15 },
  { label: '매월 20일', value: 20 },
  { label: '매월 25일', value: 25 },
]

export const JOP_TYPE = [
  { label: '공무원', value: 'CIVIL_SERVANT' },
  { label: '직장인', value: 'OFFICE_WORKER' },
  { label: '전문직', value: 'PROFESSIONAL' },
  { label: '자영업', value: 'SELF_EMPLOYED' },
  { label: '사업가', value: 'BUSINESS_OWNER' },
  { label: '아르바이트', value: 'PART_TIME' },
  { label: '주부', value: 'HOUSEWIFE' },
  { label: '무직', value: 'UNEMPLOYED' },
  { label: '기타', value: 'OTHER' },
]

export const LOAN_STATUS = [
  { label: '심사 중', value: 'UNDER_REVIEW' },
  { label: '대출 중', value: 'IN_PROGRESS' },
  { label: '계약서 작성 중', value: 'CONTRACTING' },
  { label: '송금 중', value: 'REMITTING' },
  { label: '연체 중', value: 'OVERDUE' },
  { label: '중도 상환 완료', value: 'EARLY_REPAYMENT_COMPLETED' },
  { label: '만기 상환 완료', value: 'MATURITY_REPAYMENT_COMPLETED' },
  { label: '대출 거절', value: 'REJECTED' },
]

export const LOAN_PURPOSE = [
  { label: '생활자금', value: 'LIVING_EXPENSES' },
  { label: '사업자금', value: 'BUSINESS_FUNDS' },
  { label: '카드대금상환', value: 'CARD_DEBT_PAYMENT' },
  { label: '기타부채상환', value: 'OTHER_DEBT_REPAYMENT' },
  { label: '학자금', value: 'EDUCATION_FUNDS' },
  { label: '결혼자금', value: 'MARRIAGE_FUNDS' },
  { label: '출산자금', value: 'CHILDBIRTH_FUNDS' },
  { label: '투자자금', value: 'INVESTMENT_FUNDS' },
  { label: '보험료 납부', value: 'INSURANCE_PAYMENT' },
  { label: '공과금 납부', value: 'UTILITY_PAYMENT' },
  { label: '직접 입력', value: 'DIRECT_INPUT' },
]

export const REPAYMENT_METHOD_OPTIONS = [
  { label: '근로소득 및 연금소득', value: 'EMPLOYMENT_PENSION' },
  { label: '사업소득', value: 'BUSINESS_INCOME' },
  { label: '배우자 소득', value: 'SPOUSE_INCOME' },
  { label: '퇴직금', value: 'RETIREMENT_FUNDS' },
  { label: '부동산 임대 및 양도 소득', value: 'REAL_ESTATE_INCOME' },
  { label: '금융소득(이자 및 배당)', value: 'FINANCIAL_INCOME' },
  { label: '상속/증여', value: 'INHERITANCE_GIFT' },
  { label: '직접 입력', value: 'DIRECT_INPUT' },
]

export const CREDIT_SCORE_OPTIONS = [
  { label: '650점 미만', value: 'UNDER_650' },
  { label: '650점 이상~700점 미만', value: 'RANGE_650_700' },
  { label: '700점 이상~750점 미만', value: 'RANGE_700_750' },
  { label: '750점 이상~800점 미만', value: 'RANGE_750_800' },
  { label: '800점 이상~850점 미만', value: 'RANGE_800_850' },
  { label: '850점 이상~900점 미만', value: 'RANGE_850_900' },
  { label: '900점 이상~950점 미만', value: 'RANGE_900_950' },
  { label: '950점 이상', value: 'OVER_950' },
]
export const EMPLOYMENT_TYPE = [
  { label: '정규직', value: 'PERMANENT' },
  { label: '계약직', value: 'CONTRACT' },
  { label: '사업자', value: 'BUSINESS' },
]

export const REPAYMENT_TYPE = [
  { label: '원리금균등분할상환', value: 'EQUAL_INSTALLMENT' },
  { label: '만기 일시상환', value: 'LUMP_SUM' },
]

export const LOAN_KIND_OPTIONS = [
  { label: '월급', value: 'A' },
  { label: '신용', value: 'B' },
  { label: '부동산 담보', value: 'C' },
]

export const LOAN_PURPOSE_OPTIONS = [
  { label: '생활자금', value: 'LIVING_EXPENSES' },
  { label: '사업자금', value: 'BUSINESS_FUNDS' },
  { label: '카드대금상환', value: 'CARD_DEBT_PAYMENT' },
  { label: '기타부채상환', value: 'OTHER_DEBT_REPAYMENT' },
  { label: '학자금', value: 'EDUCATION_FUNDS' },
  { label: '결혼자금', value: 'MARRIAGE_FUNDS' },
  { label: '출산자금', value: 'CHILDBIRTH_FUNDS' },
  { label: '투자자금', value: 'INVESTMENT_FUNDS' },
  { label: '보험료 납부', value: 'INSURANCE_PAYMENT' },
  { label: '공과금 납부', value: 'UTILITY_PAYMENT' },
  { label: '직접 입력', value: 'DIRECT_INPUT' },
]

export const TOTAL_ASSET_OPTIONS = [
  { label: '1억원 미만', value: 'UNDER_100M' },
  { label: '1억원~5억원 미만', value: 'RANGE_100M_500M' },
  { label: '5억원 이상', value: 'OVER_500M' },
  { label: '자산 없음', value: 'NO_ASSET' },
]

export const ANNUAL_INCOME_OPTIONS = [
  { label: '5천만원 미만', value: 'UNDER_50M' },
  { label: '5천만원~1억원 미만', value: 'RANGE_50M_100M' },
  { label: '1억원 이상', value: 'OVER_100M' },
  { label: '소득 없음', value: 'NO_INCOME' },
]

export const DEBT_SCALE_OPTIONS = [
  { label: '5천만원 미만', value: 'UNDER_50M' },
  { label: '5천만원~1억원 미만', value: 'RANGE_50M_100M' },
  { label: '1억원 이상', value: 'OVER_100M' },
  { label: '부채 없음', value: 'NO_DEBT' },
]

export const LOAN_AMOUNT_OPTIONS = [
  { label: '300만원', value: 300 },
  { label: '600만원', value: 600 },
  { label: '900만원', value: 900 },
  { label: '1200만원', value: 1200 },
  { label: '1500만원', value: 1500 },
]

export const LOAN_PERIOD_OPTIONS = [
  { label: '6개월', value: 6 },
  { label: '12개월', value: 12 },
  { label: '24개월', value: 24 },
  { label: '36개월', value: 36 },
]

export const RESIDENCE_TYPE_OPTIONS = [
  { label: '자가', value: '자가' },
  { label: '전세', value: '전세' },
  { label: '월세', value: '월세' },
]

export const HOUSING_TYPE_OPTIONS = [
  { label: '아파트/주상복합', value: '아파트/주상복합' },
  { label: '연립/다세대/다가구', value: '연립/다세대/다가구' },
  { label: '그 외', value: '그 외' },
]

export const CHECKBOX_STYLES = {
  '.chakra-checkbox__control': {
    borderRadius: '50%',
    border: '1px solid',
    borderColor: 'border.basic.2',
    _checked: {
      bg: 'primary.3',
      borderColor: 'primary.3',
      borderRadius: '50%',
    },
  },
  '.chakra-checkbox__control[data-checked]': {
    bg: 'primary.3',
    borderColor: 'primary.3',
    borderRadius: '50%',
  },
}

export const GOV_REGIONS = {
  서울특별시: [
    '강남구',
    '강동구',
    '강북구',
    '강서구',
    '관악구',
    '광진구',
    '구로구',
    '금천구',
    '노원구',
    '도봉구',
    '동대문구',
    '동작구',
    '마포구',
    '서대문구',
    '서초구',
    '성동구',
    '성북구',
    '송파구',
    '양천구',
    '영등포구',
    '용산구',
    '은평구',
    '종로구',
    '중구',
    '중랑구',
  ],
  부산광역시: [
    '강서구',
    '금정구',
    '기장군',
    '남구',
    '동구',
    '동래구',
    '부산진구',
    '북구',
    '사상구',
    '사하구',
    '서구',
    '수영구',
    '연제구',
    '영도구',
    '중구',
    '해운대구',
  ],
  대구광역시: [
    '군위군',
    '남구',
    '달서구',
    '달성군',
    '동구',
    '북구',
    '서구',
    '수성구',
    '중구',
  ],
  인천광역시: [
    '강화군',
    '계양구',
    '남동구',
    '동구',
    '미추홀구',
    '부평구',
    '서구',
    '연수구',
    '옹진군',
    '중구',
  ],
  광주광역시: ['광산구', '남구', '동구', '북구', '서구'],
  대전광역시: ['대덕구', '동구', '서구', '유성구', '중구'],
  울산광역시: ['남구', '동구', '북구', '울주군', '중구'],
  경기도: [
    '가평군',
    '고양시',
    '과천시',
    '광명시',
    '광주시',
    '구리시',
    '군포시',
    '김포시',
    '남양주시',
    '동두천시',
    '부천시',
    '성남시',
    '수원시',
    '시흥시',
    '안산시',
    '안성시',
    '안양시',
    '양주시',
    '양평군',
    '여주시',
    '연천군',
    '오산시',
    '용인시',
    '의왕시',
    '의정부시',
    '이천시',
    '파주시',
    '평택시',
    '포천시',
    '하남시',
    '화성시',
  ],
  강원특별자치도: [
    '강릉시',
    '고성군',
    '동해시',
    '삼척시',
    '속초시',
    '양구군',
    '양양군',
    '영월군',
    '원주시',
    '인제군',
    '정선군',
    '철원군',
    '춘천시',
    '태백시',
    '평창군',
    '홍천군',
    '화천군',
    '횡성군',
  ],
  충청북도: [
    '괴산군',
    '단양군',
    '보은군',
    '영동군',
    '옥천군',
    '음성군',
    '제천시',
    '증평군',
    '진천군',
    '청주시',
    '충주시',
  ],
  충청남도: [
    '계룡시',
    '공주시',
    '금산군',
    '논산시',
    '당진시',
    '보령시',
    '부여군',
    '서산시',
    '서천군',
    '아산시',
    '예산군',
    '천안시',
    '청양군',
    '태안군',
    '홍성군',
  ],
  전북특별자치도: [
    '고창군',
    '군산시',
    '김제시',
    '남원시',
    '무주군',
    '부안군',
    '순창군',
    '완주군',
    '익산시',
    '임실군',
    '장수군',
    '전주시',
    '정읍시',
    '진안군',
  ],
  전라남도: [
    '강진군',
    '고흥군',
    '곡성군',
    '광양시',
    '구례군',
    '나주시',
    '담양군',
    '목포시',
    '무안군',
    '보성군',
    '순천시',
    '신안군',
    '여수시',
    '영광군',
    '영암군',
    '완도군',
    '장성군',
    '장흥군',
    '진도군',
    '함평군',
    '해남군',
    '화순군',
  ],
  경상북도: [
    '경산시',
    '경주시',
    '고령군',
    '구미시',
    '김천시',
    '문경시',
    '봉화군',
    '상주시',
    '성주군',
    '안동시',
    '영덕군',
    '영양군',
    '영주시',
    '영천시',
    '예천군',
    '울릉군',
    '울진군',
    '의성군',
    '청도군',
    '청송군',
    '칠곡군',
    '포항시',
  ],
  경상남도: [
    '거제시',
    '거창군',
    '고성군',
    '김해시',
    '남해군',
    '밀양시',
    '사천시',
    '산청군',
    '양산시',
    '의령군',
    '진주시',
    '창녕군',
    '창원시',
    '통영시',
    '하동군',
    '함안군',
    '함양군',
    '합천군',
  ],
  제주특별자치도: ['서귀포시', '제주시'],
  세종특별자치시: ['세종특별자치시'],
} as const
